### ISSUE TITLE
An exception occurs in the redirection method in child action.

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryoTemplates#17]
When an exception occurs, [MyBaseMVController](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Frameworks/Infrastructure/Business/Presentation/MyBaseMVController.cs#L307) transfers the process to ErrorController.
Now, MyBaseMVController chooses a transition method as follows.

```c#
if (filterContext.HttpContext.Request.IsAjaxRequest())
{
    filterContext.Result = new JavaScriptResult() { Script = "location.href = '" + errorScreenPath + "'" };
}
else
{
    filterContext.Result = new RedirectResult(errorScreenPath);
}
```

But, when the exception occurs in child action using Html.Action, the redirection method (e.g. Redirect, RedirectToAction, RedirectToRoute) can not be used.
It needs to consider the transition method when the exception occurs in child action.

#### Example
```c#
if (filterContext.HttpContext.Request.IsAjaxRequest())
{
    filterContext.Result = new JavaScriptResult() { Script = "location.href = '" + errorScreenPath + "'" };
}
else if (filterContext.IsChildAction)
{
    filterContext.Result = new ContentResult() { Content = "<script>location.href = '" + errorScreenPath + "'</script>" };
}
else
{
    filterContext.Result = new RedirectResult(errorScreenPath);
}
```

**Comment by kishoreandukuri** [comment]
@daisukenishino

we modified to below code in  MyBaseMVController OnException method

>if (filterContext.HttpContext.Request.IsAjaxRequest())
{
    filterContext.Result = new JavaScriptResult() { Script = "location.href = '" + errorScreenPath + "'" };
}
else if (filterContext.IsChildAction)
{
    filterContext.Result = new ContentResult() { Content = "<script>location.href = '" + errorScreenPath + "'</script>" };
}
else
{
    filterContext.Result = new RedirectResult(errorScreenPath);
}

Do we need to do anything else to fix this issue?

Please let us know.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

This issue has been integrated into [this issued](https://github.com/OpenTouryoProject/OpenTouryo/issues/118#issuecomment-151734155).

**Comment by kishoreandukuri** [comment]
@daisukenishino 

we noticed the integration.

we think this fix is not necessary as per the below comments

>If to display "partial view" that have the controller, then session timeout detection cookie will exist and IsNewSession property states will be "true" in the second executing controller.

Therefore, the following is the limitation.
"Child view's Controller that inherited the MyBaseMVController can not be called using the HTML.Action method from main controller that has possibility that directly accessed by URL."

If you implement the main controller that has possibility that directly accessed by URL.
You can adopt the following countermeasure.

Invoke partial view by using the HTML.partial method.
Child view's controller does not inherit MyBaseMVController.


Please confirm

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>we understood this fix is not necessary as per the below comments

I do not know the contents that should be confirmed.
Please explain the contents of the above-mentioned "this fix".

**Comment by kishoreandukuri** [comment]
@daisukenishino 

But, when the exception occurs in child action using Html.Action, the redirection method (e.g. Redirect, RedirectToAction, RedirectToRoute) can not be used.
It needs to consider the transition method when the exception occurs in child action.

>Example
if (filterContext.HttpContext.Request.IsAjaxRequest())
{
    filterContext.Result = new JavaScriptResult() { Script = "location.href = '" + errorScreenPath + "'" };
}
else if (filterContext.IsChildAction)
{
    filterContext.Result = new ContentResult() { Content = "<script>location.href = '" + errorScreenPath + "'</script>" };
}
else
{
    filterContext.Result = new RedirectResult(errorScreenPath);
}

is this necessary?

please confirm

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Please read well.

If set as the limit the following,
the above correspondence is required.

> "Child view's Controller that inherited the MyBaseMVController can not be called using the HTML.Action method from main controller that has possibility that directly accessed by URL."

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Thank you for the confirmation.
we already added the code changes.
