### ISSUE TITLE
Primary Key in sample screen of 3tier data binding is always editable.

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryoTemplates#19]
I think that the ReadOnly property of the TextBox for the Primary Key should be set to **true**.

In [ProductsDetails.aspx.cs](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2013/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/ProductsDetail.aspx.cs#L370), there is the following method.

```c#
private void SetControlReadOnly(bool readOnly)
{
    // 編集可否
    // ReadOnly

    // 主キー
    this.txtProductID.ReadOnly = false;

    (The rest is omitted.)
}
```

The ReadOnly property of the TextBox for the Primary Key is always set to **false**.
Therefore, the Primary Key is always **editable**.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Because this fix related to the substance,
this fix has been moved to [OpenTouryoProject/OpenTouryo](https://github.com/OpenTouryoProject/OpenTouryo/issues/120).

This Issue will be closed.
