### ISSUE TITLE
After it will be released by setting the 01-71tag, to remove the root_VS2010 in the develop branch.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryoTemplates#23]
# Requirement
We will stop the root_VS2010(.NET4.0) 's update.
But, We were required to support continuation of the .NET3.5 (SP1).
Because some of .NET Framework will be no longer supported at January 12, 2016.
http://blogs.msdn.com/b/dotnet/archive/2014/08/07/moving-to-the-net-framework-4-5-2.aspx

Therefor, after it was released by be set 01-71tag,
- Delete root_VS2010(.NET4.0) dir contents, and commit.
- Move root_easysetup(.NET3.5) dir contents to root_VS2010(.NET3.5) dir, and commit.

Update of root_VS2010(.NET3.5) will be expected to stop after setting the next tag (01-72 or more).

**Comment by daisukenishino** [comment]
@kishoreandukuri 

You can execute this task.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>remove the root_VS2010 in the develop branch.

Shall we remove the 'root_VS2010' in the develop branch of OpenTouryoTemplates?

Please confirm our understanding.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Yes, please.
Your understanding is correct.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Yes, please. Your understanding is correct.
so the merge work should be done from root->root_easysetup->root_2012->root_2013->root_2015

Please confirm.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>so the merge work should be done from
root ---> root_easysetup ---> root_2012 ---> root_2013 ---> root_2015

That's right.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Thank you for the confirmation.

First, we delete root_2010 from develop branch and do code commit in develop branch.
Then we start merge work.
Similarly root_2010 will be deleted from other branches also or only in develop branch? 

Please confirm

**Comment by daisukenishino** [comment]
@kishoreandukuri 

- Target repository is /SymphonyTeleca/OpenTouryoTemplates/ .
- Create feature branch here, and delete root_VS2010 and commit.
- And, send pull request to [nishino branch](https://github.com/SymphonyTeleca/OpenTouryoTemplates/tree/nishino/root_VS2010) from above feature branch.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Sure, We will do as above

**Comment by kishoreandukuri** [comment]
@daisukenishino 

We deleted root_2010 as per the [instructions](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/23#issuecomment-171533201)

Please merge the pull request
https://github.com/SymphonyTeleca/OpenTouryoTemplates/issues/70

**Comment by kishoreandukuri** [comment]
@daisukenishino 

The [above](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/23#issuecomment-171533201) changes are done.

Shall we start merge work?

**Comment by daisukenishino** [comment]
@kishoreandukuri 

### Change the instructions
We were required to support continuation of the .NET3.5 (SP1).
So, I will change the instructions as following.

- Target repository is /SymphonyTeleca/OpenTouryoTemplates/ .
- Create feature branch here
  - And, delete root_VS2010 dir contents, and commit.
  - And, move root_easysetup dir contents to root_VS2010 dir, and commit.
- And, send pull request to nishino branch from above feature branch.

###  merge path
#### old  
root(3.5) ---> root_easysetup(3.5) ---> root_2010(4.0) ---> root_2012(4.5) ---> root_2013(4.5.1) ---> root_2015(4.6)

#### new  
root(3.5) ---> root_2010(3.5) ---> root_2012(4.5) ---> root_2013(4.5.1) ---> root_2015(4.6)
- Delete root_VS2010 dir contents.
- Move root_easysetup dir contents to root_VS2010 dir.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>And, delete root_VS2010 dir contents, and commit.
And, move root_easysetup dir contents to root_VS2010 dir, and commit.

Can't we do commit of both delete root_VS2010 dir contents and move root_easysetup dir contents at a time instead of two commits?

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>Can't we do commit of both delete root_VS2010 dir contents and move root_easysetup dir contents at a time instead of two commits?

It has changed. Please check.
https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/23#issuecomment-171914767

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We have checked https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/23#issuecomment-171914767
should we do separate commits for delete and move instead of in one commit?

Please confirm our understanding

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>should we do separate commits for delete and move instead of in one commit?

Yes.

**Comment by daisukenishino** [comment]
@kishoreandukuri 


>https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/23#issuecomment-171539141
Shall we start merge work?

You need to take the change until end of February in the merge work.
There is no problem to antecedently undertake the merge work.
However, please sent pullrequest later than March 1.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Thank you for the confirmation.

>You need to take the change until end of February in the merge work.
There is no problem to antecedently undertake the merge work.
However, please sent pullrequest later than March 1.

Sure, we will do as per the above instructions.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We have merged root->root_easysetup.
Shall we move merged contents of root_easysetup to root_2010?

**Comment by daisukenishino** [comment]
@kishoreandukuri 
No.
Please get it from the master branch.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Please get it from the master branch.
Ok, We will get it from master branch

**Comment by daisukenishino** [comment]
@kishoreandukuri 

##### Note:
Do not replace the [Readme.md](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2010/Readme.md).
Because the contents of Readme.md for evaluation and development is different.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Do not replace the Readme.md.
Sure

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We have done the changes as per the [instructions](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/23#issuecomment-171914767)
Please review the pull requests
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/71
https://github.com/SymphonyTeleca/OpenTouryo/pull/91

**Comment by daisukenishino2** [comment]
@kishoreandukuri 
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/71 will be merged after the https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/29 is merged.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Ok
