### ISSUE TITLE
In MVC_Sample, JavaScript and CSS files should be referenced by Scripts.Render and Styles.Render

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryoTemplates#33]
I think that the following code should be replaced by Scripts.Render method.
(If developers update the version of jquery, version mismatch occurs.)

[_CrudSampleLayout.cshtml](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Samples/WebApp_sample/MVC_Sample/MVC_Sample/Views/Shared/_CrudSampleLayout.cshtml)
```html
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.9.2.min.js"></script>
```

↓

```html
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
```

Similarly, CSS files should be referenced by Styles.Render method.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> Similarly, CSS files should be referenced by Styles.Render method.

Shall we include the CSS files [here](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Samples/WebApp_sample/MVC_Sample/MVC_Sample/App_Start/BundleConfig.cs#L51)?
```CSHTML
@Styles.Render("~/Content/themes/base/css")
```
Or 
Shall we include in separate bundle?
```CSHTML
@Styles.Render("~/bundles/jqueryui/css")
```

<b>Additional:</b>
(1)
[This file](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Samples/WebApp_sample/MVC_Sample/MVC_Sample/Views/Shared/_CrudSampleLayout.cshtml#L16) does not exists in the project.
Do we need to download this file and add it to the project?
Or
Shall we comment out the code?

(2)
The target of this correspondence is only for root_VS2012.
Or
Other versions (root_VS2013 and root_VS2015) are also required to modify. 

Please confirm and let us know.

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 

Please modify as follows in accordance with the definitions in [BundleConfig.cs](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Samples/WebApp_sample/MVC_Sample/MVC_Sample/App_Start/BundleConfig.cs#L51).

```html
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
<link href="~/Content/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
```

↓

```html
@Styles.Render("~/Content/themes/base/css")
```

><b>Additional:</b>
>(1)
>[This file](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Samples/WebApp_sample/MVC_Sample/MVC_Sample/Views/Shared/_CrudSampleLayout.cshtml#L16) does not exists in the project.
>Do we need to download this file and add it to the project?
>Or
>Shall we comment out the code? 

[This file](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Samples/WebApp_sample/MVC_Sample/MVC_Sample/Views/Shared/_CrudSampleLayout.cshtml#L16) is unnecessary.
Please comment out or erase the code.

>(2)
>The target of this correspondence is only for root_VS2012.
>Or
>Other versions (root_VS2013 and root_VS2015) are also required to modify. 

I think that other versions are also required to modify.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

Thank you for the confirmation.
We will modify accordingly and create pull request.
