### ISSUE TITLE
WinAzure_sample project is in an unstable state.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryoTemplates#36]
# Requirement
- At first, please investigate to resolve this.
- In additional requests, please add the 11_Build_WinAzure_sample.bat

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Please indicate further details about the "unstable state".
(Error message, Stacktrace, and so on. Please do not say, "Check the state of Jenkins".)

**Comment by daisukenishino** [comment]
@SandeepNayak077 

> https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36#issuecomment-190970716

Please correspond after the investigation.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36#issuecomment-191017158

Sure, we will investigate and report you.
However, this investigation is considered in the next sprint.
Because time consumption for this activity might take more time.

After completion of merge work we will start this activity.
Please let us know about your priority and opinion.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>However, this investigation is considered in the next sprint.

No problem.
Please do so.

**Comment by SandeepNayak077** [comment]
<h1> Investigation report </h1>
\-

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36#issuecomment-191113399

Thank you for your support.
When we start this task, we will provoide the investigation report [here](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36#issuecomment-191137466).

**Comment by daisukenishino** [comment]
@SandeepNayak077 

In additional requests, please add the 11_Build_WinAzure_sample.bat

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Ok, while working on this task, 
We will create a build system (11_Build_WinAzure_sample.bat) for WinAzure_sample.
Please add a description about this in the [above requirement section](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36#issuecomment-199698264)

**Comment by daisukenishino** [comment]
@SandeepNayak077 

see : https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36#issue-137525143

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Yes, its accepted.
Thank you.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

see : https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-207150633

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-207150633

Sure, we will be waiting for your requirements.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

- Please fill in [that column](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36#issuecomment-191137466).
- [Merge to WinAzure_sample](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-206791357) is required.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Unstable state is resolved.
However, you must perform the merge because the merge is not completed.
- [WebApp_sample/ProjectX_sample](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2013/programs/C%23/Samples/WebApp_sample/ProjectX_sample) ---> [WinAzure_sample/ProjectX_sample](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2013/programs/C%23/Samples/WinAzure_sample/ProjectX_sample)

**Comment by SandeepNayak077** [comment]
@daisukenishino 

>https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36#issuecomment-221195600

We have checked the status of this merge work.
All files have been merged and there is no pending merge work.

Please close this issue.
