### ISSUE TITLE
Nuget correspondnce for root_VS2012 and root_VS2013.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryoTemplates#37]
# Requirement
Remove the packages folder by nuget correspondance of sample programs.
This correspondance can significantly reduce the capacity of downloaded ZIP file.

Please check whether it is possible to correspond with VS2012 and VS2013.
Please correspondence, if it possible.

### List of the contained pullrequest 
- [Did NuGet correspondence in the frameworks of root_VS2012 #126](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126)
- [Did NuGet correspondence in the frameworks of root_VS2013 #127](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/127)
- [Resolved Issues notified in Sample program SPA_Sample and MVC_Sample #129](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/129)
- [Resolved Issues notified in Sample program SPA_Sample and MVC_Sample #130](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/130)
- [Modification of Readme.md associated with the nuget correspondence. #131](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/131)

**Comment by daisukenishino** [comment]
@SandeepNayak077 

The following two pullrequest have been merged.
However, @yusukemaegawa has requested the additional request.
The contents of the request  is that he want you to correspond framework side.

If possible to correspond in a short time,
I will incorporate this correspondence to the "01-72" version.
Please tell me about how long takes in this correspondence.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Please prioritize **the release of 01-72 version**.

I think that your "merge task" takes a bit of a while.
If "nuget correspondence" in this time catches the release of 01-72 version, please deal with my request.
If not, please deal with for the next version.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/37#issuecomment-199732600
> If possible to correspond in a short time,

Yes, it is possible.
We can send pull request by EOD today.
And we will move the merge work of root_VS2012--> root_VS2013-->root_VS2015 in the next sprint.
Is this ok?
Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>We can send pull request by EOD today.

Please do so.
I merge [the pull request](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/41), after merge the additional pullrequest.

>Is this ok?

OK.
Please start in the beginning of the next sprint.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Sure, thank you for the confirmation.
