### ISSUE TITLE
Provides a VB version of the MVC base class and template.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryoTemplates#45]
# Requirement
Provides a VB version of the MVC base class and template.

### Target is root_VS2012

Following is C# version of the MVC base class and template.
Please migrate this as VB version.

##### MVC base class
- [MyBaseMVController](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2012/programs/C%23/Frameworks/Infrastructure/Business/Presentation/MyBaseMVController.cs)

##### MVC template.
- [MVC_Sample](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2012/programs/C%23/Samples/WebApp_sample/MVC_Sample)

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We have created [pull request#159](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/159),
Please review and let us know.
