### ISSUE TITLE
Setting of UseIISExpress has not been unified.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryoTemplates#62]
# Sumally
Setting of UseIISExpress has not been unified.

## Current state
The check result in current state, it has been configured such as following.

- All *.csproj is set as "\<UseIISExpress\>true\</UseIISExpress\>"
  - https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample.csproj#L17
  - https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2013/programs/C%23/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample.csproj#L17
  - https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2015/programs/C%23/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample.csproj#L17
- All *.vbproj is set as "\<UseIISExpress\>false\</UseIISExpress\>"
  - https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/VB/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample.vbproj#L18
  - https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2013/programs/VB/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample.vbproj#L18
  - https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2015/programs/VB/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample.vbproj#L18

If the answer for your question, we need to consider what should be this setting.

## Investigation result of VS default settings
All of the WebForm and MVC settings that is excluded VS2010 are consistent to use IISExpress such as the following.

### VS2010 C&#35; and VB
```XML
    <UseIISExpress>false</UseIISExpress>
・・・
        <WebProjectProperties>
          <UseIIS>False</UseIIS>
          <AutoAssignPort>True</AutoAssignPort>
          <DevelopmentServerPort>XXXXX</DevelopmentServerPort>
          <DevelopmentServerVPath>/</DevelopmentServerVPath>
          <IISUrl>
          </IISUrl>
          <NTLMAuthentication>False</NTLMAuthentication>
          <UseCustomServer>False</UseCustomServer>
          <CustomServerUrl>
          </CustomServerUrl>
          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
        </WebProjectProperties>
```

### VS2012 C&#35; and VB
```XML
    <UseIISExpress>true</UseIISExpress>
    <IISExpressSSLPort />
    <IISExpressAnonymousAuthentication />
    <IISExpressWindowsAuthentication />
    <IISExpressUseClassicPipelineMode />
・・・
        <WebProjectProperties>
          <UseIIS>True</UseIIS>
          <AutoAssignPort>True</AutoAssignPort>
          <DevelopmentServerPort>0</DevelopmentServerPort>
          <DevelopmentServerVPath>/</DevelopmentServerVPath>
          <IISUrl>http://localhost:XXXXX/</IISUrl>
          <NTLMAuthentication>False</NTLMAuthentication>
          <UseCustomServer>False</UseCustomServer>
          <CustomServerUrl>
          </CustomServerUrl>
          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
        </WebProjectProperties>
```

### VS2013 C&#35; and VB
```XML
    <UseIISExpress>true</UseIISExpress>
    <IISExpressSSLPort />
    <IISExpressAnonymousAuthentication />
    <IISExpressWindowsAuthentication />
    <IISExpressUseClassicPipelineMode />
・・・
        <WebProjectProperties>
          <UseIIS>True</UseIIS>
          <AutoAssignPort>True</AutoAssignPort>
          <DevelopmentServerPort>XXXXX</DevelopmentServerPort>
          <DevelopmentServerVPath>/</DevelopmentServerVPath>
          <IISUrl>http://localhost:XXXXX/</IISUrl>
          <NTLMAuthentication>False</NTLMAuthentication>
          <UseCustomServer>False</UseCustomServer>
          <CustomServerUrl>
          </CustomServerUrl>
          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
        </WebProjectProperties>
```

### VS2015 C&#35; and VB
```XML
    <UseIISExpress>true</UseIISExpress>
    <IISExpressSSLPort />
    <IISExpressAnonymousAuthentication />
    <IISExpressWindowsAuthentication />
    <IISExpressUseClassicPipelineMode />
・・・
        <WebProjectProperties>
          <UseIIS>True</UseIIS>
          <AutoAssignPort>True</AutoAssignPort>
          <DevelopmentServerPort>XXXXX</DevelopmentServerPort>
          <DevelopmentServerVPath>/</DevelopmentServerVPath>
          <IISUrl>http://localhost:XXXXX/</IISUrl>
          <NTLMAuthentication>False</NTLMAuthentication>
          <UseCustomServer>False</UseCustomServer>
          <CustomServerUrl>
          </CustomServerUrl>
          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
        </WebProjectProperties>
```

# Modification policy
Please modify after determining the modification policy.

**Comment by yusukemaegawa** [comment]
@daisukenishino

I am planning to set the IISExpress setting as follows:
### Visual Studio 2010
- Not use IIS Express. (Use ASP.NET development server.)
- Fix port number.
    - In C# sample, fix port number to 9999.
    - In VB sample, fix port number to 9997.

I do not intend to add any change to ProjectX_sample.csproj and ProjectX_sample.vbproj.

### Visual Studio 2012 or later
- Use IIS Express.
- Fix port number.
    - In C# sample, fix port number to 9999.
    - In VB sample, fix port number to 9997.

I intend to revise ProjectX_sample.csproj and ProjectX_sample.vbproj as follows.
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
(omit)
    <UseIISExpress>true</UseIISExpress>
    <IISExpressSSLPort />
    <IISExpressAnonymousAuthentication />
    <IISExpressWindowsAuthentication />
    <IISExpressUseClassicPipelineMode />
  </PropertyGroup>
(omit)
  <ProjectExtensions>
    <VisualStudio>
      <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}">
        <WebProjectProperties>
          <UseIIS>True</UseIIS>
          <AutoAssignPort>False</AutoAssignPort>
          <DevelopmentServerPort>[port number]</DevelopmentServerPort>
          <DevelopmentServerVPath>/ProjectX_sample</DevelopmentServerVPath>
          <IISUrl>http://localhost:[port number]/ProjectX_sample/</IISUrl>
          <NTLMAuthentication>False</NTLMAuthentication>
          <UseCustomServer>False</UseCustomServer>
          <CustomServerUrl>
          </CustomServerUrl>
          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
        </WebProjectProperties>
      </FlavorProperties>
    </VisualStudio>
  </ProjectExtensions>
(omit)
</Project>
```

Please confirm.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

>https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/62#issuecomment-251603357
・・・
I am planning to set the IISExpress setting as follows:
・・・
Please confirm.

It is consistent to my expectations.
But, following settings are different from some of status quo.

```XML
<AutoAssignPort>False</AutoAssignPort>
<DevelopmentServerPort>[port number]</DevelopmentServerPort>
<DevelopmentServerVPath>/ProjectX_sample</DevelopmentServerVPath>
<IISUrl>http://localhost:[port number]/ProjectX_sample/</IISUrl>
```

Therfore, please check that the initialized CRUD screen had shown between the root_VS2012 and 2015.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I confirmed that CRUD screen is shown and CRUD process works normally in all version (root_VS2012, root_VS2013, root_VS2015) and both language (C#, VB).

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Thank you for confirmation.
If that's, I will wait for your pull-request.
