### ISSUE TITLE
The restoring NuGet packages will fail when unzipping template's zip file to desktop

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryoTemplates#71]
# Requirement
The restoring NuGet packages that are used in ASPNETWebService project will fail when unzipping template's zip file to desktop.

Because the folder path to `ASPNETWebService.sln` is too long, the restoring NuGet packages that are used in ASPNETWebService project will fail. So, the build of `ASPNETWebService.sln` will fail.
When unzipping template's zip file to C drive, the restoring NuGet packages and the build of `ASPNETWebService.sln` will succeed.

Please consider shortening this folder path.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Which ASPNETWebService?
Is it the long one? Or both?
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2015/programs/C%23/Samples/WS_sample/ASPNETWebService
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2015/programs/C%23/Frameworks/Infrastructure/ServiceInterface/ASPNETWebService

Let me discuss it later.

**Comment by daisukenishino2** [comment]
@yusukemaegawa 

there is the following background.

- ファイルやパスの文字列長と文字コードの問題 - マイクロソフト系技術情報 Wiki
https://techinfoofmicrosofttech.osscons.jp/index.php?%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%84%E3%83%91%E3%82%B9%E3%81%AE%E6%96%87%E5%AD%97%E5%88%97%E9%95%B7%E3%81%A8%E6%96%87%E5%AD%97%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E5%95%8F%E9%A1%8C

Let me discuss it later.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

この問題は、本リポジトリの zip ファイルを C ドライブ直下ではなく、デスクトップなどに解凍し、ビルドバッチファイルを実行した場合に起きる現象です。

NuGet パッケージを取得する際に、一部のファイルが Windows のファイルパスの長さ制限である 260 文字を超えてしまい、その NuGet パッケージのダウンロードに失敗し、結果としてその NuGet パッケージを使用しているプログラムがコンパイルエラーになります。

プロジェクト名を短くするなどにより、エラーは回避できるかもしれませんが、根本的な解決にはなりません。(デスクトップよりももっと階層の深いフォルダーでビルドバッチファイルを実行したら、結局同じ現象が発生する)

このため、本 Issue への対応としては、プロジェクト名を短くするということではなく、Readme などで **C ドライブ直下以外に配置すると、プログラムのビルド時などで、Windows のファイルパスの最大文字長を超え、ビルドに失敗することがあります。このため、C ドライブ直下に配置するようにしてください。** のような注意喚起することだと思います。(場所としては、[テンプレート・ベースの配置](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2017/Readme.ja.md#%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%83%99%E3%83%BC%E3%82%B9%E3%81%AE%E9%85%8D%E7%BD%AE)あたりがいいかもしれません。)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

- 上記、了解しました。
- 本issue、
  - [こちらのマイルストーン](https://github.com/OpenTouryoProject/OpenTouryoTemplates/milestone/6)に移動しました。
  - 以下を修正対象と認識しました。

### OpenTouryo
#### root
- [README.md](https://github.com/OpenTouryoProject/OpenTouryo/blob/master/root/README.md#deploy-open-touryo)
- [Readme.ja.md](https://github.com/OpenTouryoProject/OpenTouryo/blob/master/root/Readme.ja.md#open-%E6%A3%9F%E6%A2%81%E3%81%AE%E9%85%8D%E7%BD%AE)

### OpenTouryoTemplates
#### root_VS2015
- [README.md](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2015/README.md#deploy-open-touryo-template-base)
- [Readme.ja.md](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2015/Readme.ja.md#%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%83%99%E3%83%BC%E3%82%B9%E3%81%AE%E9%85%8D%E7%BD%AE)

#### root_VS2017
- [README.md](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2017/README.md#deploy-open-touryo-template-base)
- [Readme.ja.md](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2017/Readme.ja.md#%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%83%99%E3%83%BC%E3%82%B9%E3%81%AE%E9%85%8D%E7%BD%AE)
