### ISSUE TITLE
Merge the develop branch (OpenTouryoProject/OpenTouryo) changes to the template.

### ISSUE THREAD

**Issue by daisukenishino2** [OpenTouryoProject/OpenTouryoTemplates#72]
# Requirement
https://github.com/OpenTouryoProject/OpenTouryo/pull/271

### TODO
+ After completing the review of OpenTouryo, merge the develop branch into the master branch
+ Create and register OpenTouryo's NuGet package.
+  Merge OpenTouryo's changes into the **OpenTouryoTemplates** develop branch.
+  Upgrade NuGet package of **OpenTouryoTemplates** in develop branch.
+  Merge the develop branch of **OpenTouryoTemplates** into the master branch.

### Policy
- NuGetの依存関係パッケージのポリシー - Open 棟梁 Wiki
https://opentouryo.osscons.jp/index.php?NuGetの依存関係パッケージのポリシー

**Comment by daisukenishino** [comment]
# Detail
- Make Business, CustomControl and Tools use NuGet (Add packages.config)
- Fixed build batch (Remove execution build of NuGet Package and Add execution of NuGet restore)
- Delete testPublic processing (WebForms template)
