### ISSUE TITLE
The url to license file is not found

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryoTemplates#77]
The license is indicated as follows in [_ViewStart.cshtml](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2017/programs/VB/Samples/WebApp_sample/MVC_Sample/MVC_Sample/Views/_ViewStart.cshtml) and other files. But the following url is not found.

```html
// 以下のLicenseに従い、このProjectをTemplateとして使用可能です。Release時にCopyright表示してSublicenseして下さい。
// https://github.com/OpenTouryoProject/OpenTouryo/blob/master/license/LicenseForTemplates.txt
```

The above comment is not described in the program of C# version.
I recognize that this program is Apache License as indicated in [this file](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/license/LICENSE.txt).

Please modify the above comment to match an actual condition.

**Comment by daisukenishino** [comment]
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/VB/Samples/WebApp_sample/MVC_Sample/MVC_Sample/Views/_ViewStart.cshtml
