### ISSUE TITLE
Add root_VS2019 folder 

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryoTemplates#79]
# Requirement
- Same as #68
- Use the VS2019 & net48.

**Comment by daisukenishino2** [comment]
# Change point

## BAT file that generates a certificate file
\root\files\resource\X509

## BAT file that build libraries.
\root\programs\VB\*.bat

## Performance improvement of automatically generated Dao.
- \root\files\tools\DGenTemplates

- \CS\Samples\...\WebForms_Sample\AppCode\sample\Business\LayerB.cs
- \CS\Samples\...\WebForms_Sample\AppCode\sample\Dao\DaoShippers.cs

- \VB\Samples\...\WebForms_Sample\AppCode\sample\Business\LayerB.vb
- \VB\Samples\...\WebForms_Sample\AppCode\sample\Dao\DaoShippers.vb

## Dealing with EventHandler double registration problem
- \CS\...\Business\RichClient\Presentation\MyBaseControllerWin.cs
- \CS\Samples\WS_sample\WSClient_sample\WSClientWin2_sample\Form1.cs

- \VB\...\Business\RichClient\Presentation\MyBaseControllerWin.vb
- \VB\Samples\WS_sample\WSClient_sample\WSClientWin2_sample\Form1.vb

## Get processing for controller and action name in WebAPI.
- \CS\...\MyBaseAsyncApiController.cs
- \CS\...\MyBaseAsyncApiControllerCore.cs

## Split PubCmnFunction.

### StringVariableOperator
- \DeployZipPackWithHTTP\Program.cs

- \CS\Samples\Bat_sample\...\*.cs
- \VB\Samples\Bat_sample\...\*.vb

- \CS\Samples4NetCore\Legacy\Bat_sample\

### StackFrameOperator
- \CS\...\MyBusinessApplicationExceptionMessage.cs
- \CS\...\MyBusinessSystemExceptionMessage.cs

- \VB\...\MyBusinessApplicationExceptionMessage.vb
- \VB\...\MyBusinessSystemExceptionMessage.vb

## WS_sample\ASPNETWebService

### Added method attribute.
- \CS\Samples\WS_sample\...\ASPNETWebService\Controllers\ValuesController.cs
- \CS\Samples4NetCore\...\ASPNETWebService\Controllers\ValuesController.cs

### Public.Dbg → Public.Diagnostics.
- \CS\Samples\WS_sample\...\ASPNETWebService\Controllers\JsonController.cs

### JwtToken → AccessToken
- \CS\Samples\WS_sample\...\ASPNETWebService\Controllers\JsonController.cs
