### ISSUE TITLE
The problem of the conduct on the Tutorial.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryoTemplates#8]
Problem of the build process.
---
- Build of the VB side needs to execute after the build of the C# side.
- There is a need that reapplication reference of "System.Web.Mvc" in root_VS2013 at some environment. Perhaps, there is a mismatch, depending on environment on the version of the binary.
- WPF Tool Kit is unnecessary in .NET4.0 more, but implementation using WPF Tool Kit have been merged. Remove the reference set of WPFToolkit, Please be replaced with DataGrid in WPF standard shipped from DataGrid of WPFToolkit.
```XML
<my:DataGrid AutoGenerateColumns="True" Canvas.Left="313" Canvas.Top="6.33" Height="437.67" Name="dataGrid1" Width="442" ItemsSource="{Binding}" xmlns:my="http://schemas.microsoft.com/wpf/2008/toolkit" />
<DataGrid AutoGenerateColumns="True" Canvas.Left="313" Canvas.Top="6.33" Height="437.67" Name="dataGrid1" Width="442" ItemsSource="{Binding}"/>
```
- Certificate pfx (PKCS12) format does not exist in rich client project. Must Re-generate the certificate of pfx (PKCS12) format.  
e.g.:https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2010/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWPFbap_sample
- Exists environment that can not Build using the MSBuild. Cause unknown.

**Comment by supragyan** [comment]
Do we need to change in VS2013's readme text to running under -IIS. 
Please confirm.

**Comment by daisukenishino** [comment]
HISOL will conduct that correspondence of this problem.
Therefor, HISOL will modify VS2013's readme text.
