### ISSUE TITLE
The compilation of "WSClientWinStore_samples" fails

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryoTemplates#9]
# Phenomenon
The compilation of "WSClientWinStore_samples" fails.

# Details
- The following project included in the solution does not exist.
    - WinStoreBusiness.csproj
    - WinStorePublic.csproj
    - WinStoreFramework.csproj
- The **Touryo.Infrastructure.Business.ServiceInterface.WcfDataContract.Rest** namespace which [CRUDPage_jn](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2013/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWinStore_samples/WSClientWinStore_sample/Views/CRUDPage_jn.xaml.cs#L19) and [CRUDPage_xl](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2013/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWinStore_samples/WSClientWinStore_sample/Views/CRUDPage_xl.xaml.cs#L19) refer to is not found.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

\>> The following project included in the solution does not exist.

As per we know, earlier there were "Silverlight" and "WinStore" projects.
But now the above two projects are missing in the following location
<link>https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2013/programs/C%23/Frameworks

**Comment by yusukemaegawa** [comment]
@SandeepNayak077

["Portable Class Library" support is completed.](https://github.com/OpenTouryoProject/OpenTouryo/pull/83) says that "Silverlight" and "WinStore" projects have been merged to "Portable Class Library".
So, the projects with the name beginning with "WinStore" in "WSClientWinStore_samples.sln" should be removed.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

Yes, you are correct.
We will remove the projects related to "WinStore" in "WSClientWinStore_samples.sln".

Shall we do the above modification in both "root_2012" and "root_2013" ?
please confirm.

**Comment by yusukemaegawa** [comment]
@yusukemaegawa

>Shall we do the above modification in both "root_2012" and "root_2013" ?

Yes.
The same modification is necessary in both "root_VS2012" and "root_VS2013".

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

Thank you for the confirmation.
We will chnage it and create new pull request.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

Because of some Visual Studio software issue and some internal work,
We will try to complete the above modification by today,
If not possible, then we will complete it by tomorrow.
Sorry for the inconvenience caused.

**Comment by yusukemaegawa** [comment]
Okey.
That's quite alright.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

Thank you for understanding the situation.
We have done code commit and created pull request.

**Comment by yusukemaegawa** [comment]
@SandeepNayak077

Thank you for your pull request.
The reference errors of "WSClientWinStore_samples" have been fixed by this modification.
But, the compilation error still remains.

In [StandardStyles.xaml](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/winstoresample/root_VS2013/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWinStore_samples/WSClientWinStore_sample/Common/StandardStyles.xaml#L1765), it is described as follows.

```xml
<ToolTipService.Placement>マウス</ToolTipService.Placement>
```

The inner text of "ToolTipService.Placement" tag should be "Mouse" instead of "マウス".

**Comment by SandeepNayak077** [comment]
@yusukemaegawa 

\>> But, the compilation error still remains.

Yes, we also got the same compilation error.
We then changed from "マウス" to "Mouse", 
and successfully done build process.
Because our Visual Studio run on English environment.

We assumed that in Visual Studio supported in Japanese environmet, 
may accept "マウス" character instead of "Mouse".
So, we did not modified any Japanese characters in that solution.


\>> The inner text of "ToolTipService.Placement" tag should be "Mouse" instead of "マウス".

Do we need to change from "マウス" to "Mouse" ?

Please confirm, 
we will do changes and do code commit.

**Comment by yusukemaegawa** [comment]
@SandeepNayak077

I am sorry for the delay in my reply.
>Do we need to change from "マウス" to "Mouse" ?

Yes, please.

**Comment by SandeepNayak077** [comment]
@yusukemaegawa

\>> I am sorry for the delay in my reply.

Its ok, no problem.

\>> Yes, please.

Thank you for the confirmation.
We will do it by today.
